networks:
  local:
    driver: bridge

services:
  local-project:
    build: ./docker
    volumes:
      - /Users/Ryttis/Sites/code/task-code-review:/var/www/html/localhost
    networks:
      - local
    environment:
      PHP_IDE_CONFIG: "serverName=Project"
      XDEBUG_SESSION: PHPSTORM
    container_name: local_project

  local-nginx:
    image: nginx:1.23
    volumes:
      - /Users/Ryttis/Sites/code/task-code-review:/var/www/html/localhost
      - /Users/Ryttis/Sites/code/task-code-review/docker/docker/localhost.conf:/etc/docker/conf.d/default.conf
    networks:
      - local
    ports:
      - "8081:80"
    container_name: local_nginx
    depends_on:
      - local-project

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
